### ISSUE TITLE
Don't put typings as dependencies

### ISSUE THREAD

**Issue by pocesar** [service-mocker/service-mocker#27]
## Issue Summary

Right now it's impossible to use Typescript@next and this library, when using "dom" in the "lib" of tsconfig.json, because it's user defined typings of typings already defined in `lib.dom.d.ts`, like Fetch and Streams. 

## Expected Behavior

Put the whatg and service workers in peerDependencies, so at least the compile time won't choke

## Current Behavior

Project won't compile because of conflicting redefinitions from whatg and service_worker_api typings and lib.dom.d.ts 'stdlib'

## Steps to Reproduce

1. Install typescript@next
2. Set tsconfig.json "compilerOptions.lib" to `["dom"]`
3. Install service-mocker
3. Try to compile project

**Comment by idiotWu** [comment]
Typings as dependencies or not has been confusing me since the very first day I started using typescript, especially these DOM-related typings 😢.

If you exclude `service_worker_api` from typings, you are still not able to compile since we are actually using it. And if you don't, you will get tons of conflicts.

@VincentBel I'm just thinking about switching back to babel. This project can't even be compiled with typescript 2.2:

<summary>
<details>
<pre>
ERROR in ./src/client/modern/client.ts
(23,9): error TS2322: Type 'ServiceWorker | null' is not assignable to type 'ServiceWorker'.
  Type 'null' is not assignable to type 'ServiceWorker'.

ERROR in ./src/client/modern/client.ts
(74,9): error TS2322: Type 'ServiceWorker | null' is not assignable to type 'ServiceWorker'.
  Type 'null' is not assignable to type 'ServiceWorker'.
</pre>
</details>
</summary>

**Comment by pocesar** [comment]
I'm using `target: "es5"` and `module: "system"`, with `lib: [ "dom", "es2015" ]`. what I'm doing right now is to manually delete the node_modules/@types/whatg-* and service_worker_api, and manually patched service-mocker .d.ts setting to `: any` any ServiceEvent mention

**Comment by idiotWu** [comment]
@pocesar you can also use the `types` option in tsconfig.json: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by pocesar** [comment]
indeed, but then service-mocker definition files throw errors because of missing types (and they forcefully mentions `/// <reference types="whatg-fetch" />` at the top)

**Comment by idiotWu** [comment]
Yeah I know. Actually it was me who rewrote that typing 😂

**Comment by idiotWu** [comment]
It seems that [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) is still using ts 2.0/2.1. I'll send a PR to remove the triple slashes declaration when they are ready for ts 2.2+, keep tracking 😄

**Comment by idiotWu** [comment]
@pocesar hey dude, the conflicts seem to be fixed through DefinitelyTyped/DefinitelyTyped#15222, but I cannot find the new typings in that repo 😨

**Comment by idiotWu** [comment]
@VincentBel ts2.2 now supports service worker API, we need to refactor the workflow

**Comment by idiotWu** [comment]
@pocesar I'm wondering how you can compile both the client and server side ts codes with single `tsconfig.json`? They are running on different context in ts2.2, i.e. `lib.dom` & `lib.webworker`.

**Comment by VincentBel** [comment]
@idiotWu I'll try to solve this problem tomorrow..

**Comment by idiotWu** [comment]
@pocesar 2.0.0 has shipped 🎉
