### ISSUE TITLE
Docs website is broken

### ISSUE THREAD

**Issue by egoist** [service-mocker/service-mocker#51]
![2018-04-03 11 54 00](https://user-images.githubusercontent.com/8784712/38228396-b9d7beea-3735-11e8-95ac-a87db69e49f2.png)

https://github.com/service-mocker/service-mocker/blob/3650157256b9666cafdddfa10cc328ba66a3880c/docs/index.html#L27

not sure why, but it seems `window.docute` does not exist in https://unpkg.com/docute@2.7.1/dist/docute.js, maybe bump version or use https://cdn.jsdelivr.net/npm/docute@2.7.1/dist/docute.js instead 😅

**Comment by vincentbel** [comment]
Docs website doesn't throw the error on my machine, may it be caused by some browser extensions? 😆 

![image](https://user-images.githubusercontent.com/6076919/38235255-093519de-3753-11e8-97f1-33b37886cf92.png)

And `window.docute` does exist on <https://unpkg.com/docute@2.7.1/dist/docute.js>:

![image](https://user-images.githubusercontent.com/6076919/38235272-1b0dc89a-3753-11e8-8ee7-f9c96bd8163d.png)

**Comment by egoist** [comment]
Oh my bad, it's all good now after I cleared browser cache.
